server:
  servlet:
    contextPath: /NAPAS_API
  port: 8083
kai:
  name: NAPAS_API
  key: napas861klfoni1ezxl5f2ck771
  threadName: NAPAS_API
  pollSize: 100
  error:
    code999: "Internal Server Error {0}"
    code998: "Timeout {0}"
    code701: "API not exist"
    code700: "API key not exists"
    code803: "RequestId not exist"
    code996: "Error insert request to DB#{0}"
    code804: "Input missing.Field {0} is required"
    code09: "MISSING FIELD#{0}"
    code91: "No account found#{0}"
    code11: "Duplicate Transaction"
    code12: "Transaction Invalid"
spring:
  application:
    name: NAPAS_API
  database:
    postgres: true
  postgredatasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://103.57.222.76:5432/doantotnghiep?currentSchema=napas_api
    username: postgres
    password: 123456
    maximum-pool-size: 50
    idleTimeout: 120000
    minimumIdle: 10
  jpa:
    show-sql: false
    open-in-view: false
dbinfo:
  apiRequest: request_in
  apiResponse: request_out
  transaction: '"napas_transaction"'
